#!/bin/bash
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=MENSAGEM_PADRAO > MENSAGEM_PADRAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=MENSAGEM > MENSAGEM.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_MENSAGEM > VALIDA_MENSAGEM.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=AUDITA_GRAVACAO > AUDITA_GRAVACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=HABILITA_GRAVACAO > HABILITA_GRAVACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=AUDITA_EXCLUSAO > AUDITA_EXCLUSAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=AUDITORIA > AUDITORIA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=CRIA_RECORDGROUP > CRIA_RECORDGROUP.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VERIFICA > VERIFICA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=CENTRALIZA_FORM > CENTRALIZA_FORM.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_ERROS > VALIDA_ERROS.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GLOBAL > PACK_GLOBAL.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_TELA > PACK_TELA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_TELA > PACK_TELA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_MOVIMENTACAO > VALIDA_MOVIMENTACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_SOLICITACAO > VALIDA_SOLICITACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRUPO > PACK_GRUPO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRUPO > PACK_GRUPO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=ADICIONA_GRUPO > ADICIONA_GRUPO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_PROCEDIMENTOS > PACK_PROCEDIMENTOS.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_PROCEDIMENTOS > PACK_PROCEDIMENTOS.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_DUPLICADOS > VALIDA_DUPLICADOS.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=ENVIA_EMAIL > ENVIA_EMAIL.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_AUDITORIA > PACK_AUDITORIA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_AUDITORIA > PACK_AUDITORIA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRAVALIBERACAO > PACK_GRAVALIBERACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRAVALIBERACAO > PACK_GRAVALIBERACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=DEFINIR_ROUND > DEFINIR_ROUND.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=CANCELAR_ITEMCOMPRA > CANCELAR_ITEMCOMPRA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_CONTA_ORCAMENTO > VALIDA_CONTA_ORCAMENTO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=MANIPULA_CAMPO > MANIPULA_CAMPO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRUPO_NEGOCIO > PACK_GRUPO_NEGOCIO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_GRUPO_NEGOCIO > PACK_GRUPO_NEGOCIO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_DUPLICADOS_NEGOCIO > VALIDA_DUPLICADOS_NEGOCIO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=ADICIONA_GRUPO_NEGOCIO > ADICIONA_GRUPO_NEGOCIO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=IMPORTA_ARQUIVO > IMPORTA_ARQUIVO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=RETORNA_NOME_ARQUIVO > RETORNA_NOME_ARQUIVO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=CARREGA_PLANILHA_CENTROCUSTO > CARREGA_PLANILHA_CENTROCUSTO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_EMPCC > VALIDA_EMPCC.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_CENTROCUSTO > VALIDA_CENTROCUSTO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_ORCAMENTO_IMP > VALIDA_ORCAMENTO_IMP.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_MOV_IMP > VALIDA_MOV_IMP.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_NEGOCIO_IMP > VALIDA_NEGOCIO_IMP.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=MSG_CONFIRMACAO > MSG_CONFIRMACAO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=VALIDA_AUTORIZADORCOMPRA > VALIDA_AUTORIZADORCOMPRA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=INFORMA_PROJETO > INFORMA_PROJETO.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=MAX_CALL_FORM > MAX_CALL_FORM.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_PREITEMCOMPRA > PACK_PREITEMCOMPRA.mm
mapperidea generate maxicon-forms2 mm procedures className=COM001 methodName=PACK_PREITEMCOMPRA > PACK_PREITEMCOMPRA.mm
